apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.35.0
    extraMounts:
      - hostPath: .github/workflows/kind/registry-cri-host.toml
        containerPath: /etc/containerd/hosts/localhost_5001_/hosts.toml
        readOnly: true
containerdConfigPatches:
  - |
    [plugins.'io.containerd.cri.v1.images'.registry]
      config_path = '/etc/containerd/hosts'
